import { useEffect, useState } from "react";

const localValue = (date) => new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16);
export default function ExportDialog() {
    const [data, setData] = useState(null); const [ephemeris, setEphemeris] = useState(null);
    useEffect(() => { const open = (event) => { setData(event.detail); const now = new Date(); setEphemeris({ start: localValue(now), end: localValue(new Date(now.getTime() + 86400000)), step: 10, format: "oem", propagator: "sgp4" }); }; const close = () => setData(null); window.addEventListener("orbit:export-open", open); window.addEventListener("orbit:export-close", close); return () => { window.removeEventListener("orbit:export-open", open); window.removeEventListener("orbit:export-close", close); }; }, []);
    if (!data || !ephemeris) return null;
    const run = (type, detail = {}) => window.dispatchEvent(new CustomEvent("orbit:export-action", { detail: { type, ...detail } }));
    const update = (key, value) => setEphemeris((current) => ({ ...current, [key]: value }));
    return <div id="catalogExportModal" className="open" onMouseDown={(event) => event.target === event.currentTarget && run("close")}><section className="catalog-export-panel" role="dialog" aria-modal="true"><header><h3>Exportar {data.id}</h3><button className="catalog-close-btn" type="button" onClick={() => run("close")}>×</button></header><p>Fuente: {data.sourceFormat}</p><div className="catalog-export-actions">{data.sourceFormat === "TLE" && <button className="catalog-header-btn" type="button" onClick={() => run("tle")}>Exportar TLE</button>}{data.sourceFormat === "OMM" && <><button className="catalog-header-btn" type="button" onClick={() => run("omm-json")}>OMM JSON</button><button className="catalog-header-btn" type="button" onClick={() => run("omm-xml")}>OMM XML</button></>}{data.sourceFormat === "OEM" && <button className="catalog-header-btn" type="button" onClick={() => run("oem")}>Exportar OEM</button>}</div><section className="catalog-export-section"><h4>Exportar efemérides</h4><div className="catalog-export-grid"><label>Fecha inicio<input type="datetime-local" value={ephemeris.start} onChange={(event) => update("start", event.target.value)} /></label><label>Fecha fin<input type="datetime-local" value={ephemeris.end} onChange={(event) => update("end", event.target.value)} /></label><label>Intervalo (s)<input type="number" min="1" value={ephemeris.step} onChange={(event) => update("step", event.target.value)} /></label><label>Formato<select value={ephemeris.format} onChange={(event) => update("format", event.target.value)}>{["csv", "json", "oem"].map((value) => <option key={value}>{value}</option>)}</select></label></div><button className="catalog-action-btn" type="button" onClick={() => run("ephemeris", ephemeris)}>Exportar efemérides</button></section></section></div>;
}
