import { useEffect, useState } from "react";

const tabs = {
    general: [["name", "Nombre de capa", "text"], ["latitude_deg", "Latitud (deg)", "number"], ["longitude_deg", "Longitud (deg)", "number"], ["altitude_m", "Altitud (m)", "number"], ["min_elevation_deg", "Máscara elevación", "number"], ["coverage_radius_km", "Radio cobertura (km)", "number"]],
    radio: [["frequency_mhz", "Frecuencia (MHz)", "number"], ["tx_power_dbm", "Potencia TX (dBm)", "number"], ["tx_gain_dbi", "Ganancia TX (dBi)", "number"], ["rx_gain_dbi", "Ganancia RX (dBi)", "number"]],
    visual: [["point_size_px", "Tamaño símbolo (px)", "number"], ["point_color", "Color símbolo", "color"]],
    heatmap: []
};

export default function GroundStationDialog() {
    const [data, setData] = useState(null); const [tab, setTab] = useState("general");
    useEffect(() => { const open = (event) => { setData(event.detail); setTab("general"); }; const close = () => setData(null); window.addEventListener("orbit:ground-station-open", open); window.addEventListener("orbit:ground-station-close", close); return () => { window.removeEventListener("orbit:ground-station-open", open); window.removeEventListener("orbit:ground-station-close", close); }; }, []);
    if (!data) return null;
    const update = (key, value) => setData((current) => ({ ...current, values: { ...current.values, [key]: value } }));
    const values = data.values || {};
    return <div id="groundStationModal" className="open" onMouseDown={(event) => event.target === event.currentTarget && setData(null)}><section className="catalog-filter-panel ground-station-panel" role="dialog" aria-modal="true"><header className="catalog-filter-header"><h3>{data.editing ? "Editar estación terrestre" : "Nueva estación terrestre"}</h3><button className="catalog-close-btn" type="button" onClick={() => setData(null)}>×</button></header><nav className="ground-station-tabs">{Object.keys(tabs).map((key) => <button type="button" className={`ground-station-tab-btn${tab === key ? " active" : ""}`} key={key} onClick={() => setTab(key)}>{key === "heatmap" ? "Heat map" : key[0].toUpperCase() + key.slice(1)}</button>)}</nav><div className="catalog-filter-grid ground-station-grid">{tabs[tab].map(([key, label, type]) => <label className="catalog-filter-field" key={key}><span>{label}</span><input type={type} value={values[key] ?? ""} onChange={(event) => update(key, event.target.value)} /></label>)}{tab === "visual" && <><label className="catalog-filter-field"><span>Símbolo</span><select value={values.point_symbol || "circle"} onChange={(event) => update("point_symbol", event.target.value)}>{["circle", "square", "triangle", "diamond", "star"].map((value) => <option key={value}>{value}</option>)}</select></label><label className="catalog-filter-field checkbox"><span>Mostrar cobertura</span><input type="checkbox" checked={values.coverage_visible !== false} onChange={(event) => update("coverage_visible", event.target.checked)} /></label></>}{tab === "heatmap" && <><label className="catalog-filter-field checkbox"><span>Heat map acumulado</span><input type="checkbox" checked={values.heatmap_enabled === true} onChange={(event) => update("heatmap_enabled", event.target.checked)} /></label><label className="catalog-filter-field"><span>Densidad</span><select value={values.heatmap_density || "medium"} onChange={(event) => update("heatmap_density", event.target.value)}>{["low", "medium", "high"].map((value) => <option key={value}>{value}</option>)}</select></label></>}</div><div className="catalog-filter-actions"><button className="catalog-action-btn" type="button" onClick={() => window.dispatchEvent(new CustomEvent("orbit:ground-station-submit", { detail: values }))}>{data.editing ? "Guardar cambios" : "Crear estación"}</button></div></section></div>;
}
